import type { ElectionResult } from "./types";

export const mockResult: ElectionResult = {
  sourceId: "0",
  electionId: "0",
  round: 1,
  phase: "simulation",
  scope: "BR",
  scopeType: "country",
  office: "president",
  officeCode: "1",
  officeName: "Presidente",
  seats: 1,
  electoralQuotient: null,
  generatedAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString(),
  status: "in-progress",
  final: false,
  progress: 58.42,
  sections: { total: 0, totalized: 0, pending: 0 },
  electorate: { eligible: 0, totalized: 0, attendance: 0, abstention: 0 },
  votes: {
    total: 0,
    candidateVotes: 0,
    valid: 0,
    nominal: 0,
    partyList: 0,
    annulled: 0,
    annulledSubJudice: 0,
    blank: 0,
    nullVotes: 0,
    regularNull: 0,
    technicalNull: 0,
    canceledWithoutValidity: 0,
    withoutAnnulment: 0
  },
  candidates: [
    {
      id: "1",
      number: "00",
      name: "Candidato A",
      fullName: "Candidato A",
      party: "XX",
      partyName: "Partido X",
      votes: 32548921,
      percentage: 42.18,
      rank: 1,
      elected: false,
      status: "pending",
      destination: "valid",
      runningMates: [],
      substitutes: []
    },
    {
      id: "2",
      number: "00",
      name: "Candidato B",
      fullName: "Candidato B",
      party: "YY",
      partyName: "Partido Y",
      votes: 28341112,
      percentage: 36.73,
      rank: 2,
      elected: false,
      status: "pending",
      destination: "valid",
      runningMates: [],
      substitutes: []
    },
    {
      id: "3",
      number: "00",
      name: "Candidato C",
      fullName: "Candidato C",
      party: "ZZ",
      partyName: "Partido Z",
      votes: 9582331,
      percentage: 12.41,
      rank: 3,
      elected: false,
      status: "pending",
      destination: "valid",
      runningMates: [],
      substitutes: []
    }
  ],
  groups: []
};
